# Generated by Django 6.0.5 on 2026-05-29 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover_image', models.ImageField(blank=True, default='album_covers/album-placeholder.png', null=True, upload_to='album_covers/')),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(choices=[('blues', 'Blues'), ('classical', 'Classical'), ('country', 'Country'), ('jazz', 'Jazz'), ('other', 'Other'), ('pop', 'Pop'), ('rock', 'Rock'), ('r&B', 'R&B')], default='other', max_length=20)),
                ('producer_name', models.CharField(max_length=30)),
                ('record_label', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, max_length=600, null=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.artist')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
