# Generated by Django 5.0.6 on 2024-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_photo', models.CharField(max_length=50)),
                ('release_date', models.CharField(max_length=10)),
                ('album_genre', models.CharField(max_length=20)),
                ('producer_name', models.CharField(max_length=30)),
                ('record_label', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_id', models.CharField(max_length=200)),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_country', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
