# Generated by Django 5.0.6 on 2024-06-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_albums_artists_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album_photo', models.ImageField(upload_to='images')),
                ('release_date', models.DateField()),
                ('album_genre', models.CharField(choices=[('blues', 'Blues'), ('classical', 'Classical'), ('country', 'Country'), ('jazz', 'Jazz'), ('other', 'Other'), ('pop', 'Pop'), ('rock', 'Rock'), ('r&B', 'R&B')], default='other', max_length=20)),
                ('producer_name', models.CharField(max_length=30)),
                ('record_label', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True, max_length=600, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Albums',
        ),
        migrations.DeleteModel(
            name='Artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.artist'),
        ),
    ]
