# Generated by Django 5.0.6 on 2024-06-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_album_artist_delete_albums_delete_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artist_id',
        ),
    ]
