# Generated by Django 5.0.6 on 2024-06-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_album_artist_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_genre',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_photo',
            field=models.CharField(max_length=100),
        ),
    ]
