# Generated by Django 5.0.6 on 2024-06-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_genre_album_album_genre_album_artist'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='album',
        ),
        migrations.AlterModelTable(
            name='artist',
            table='artist',
        ),
    ]
