# Generated by Django 5.0.6 on 2024-06-16 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_album_table_alter_artist_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='album_photo',
            new_name='photo',
        ),
    ]
