# Generated by Django 5.0.6 on 2024-06-16 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_album_genre_album_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='photo',
        ),
    ]
