# Generated by Django 6.0.5 on 2026-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_album_name_album_cover_image_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, default='album_covers/album-cover-placeholder.png', null=True, upload_to='album_covers/'),
        ),
    ]
